import os
import re
import subprocess
import tempfile
from crewai.flow.flow import Flow, listen, start, router, or_
from .crew import AgileCoderCrew

class AgileCoderFlow(Flow):
    MAX_SPRINTS = 3

    def execute_code_deterministically(self, code: str, tests: str) -> str:
        full_script = f"{code}\n\n{tests}\n\nif __name__ == '__main__':\n    import unittest\n    unittest.main(exit=False)\n"

        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as temp_file:
            temp_file.write(full_script)
            temp_path = temp_file.name

        try:
            result = subprocess.run(['python', temp_path], capture_output=True, text=True, timeout=5)
            if result.returncode == 0:
                return "PASSED"
            else:
                return f"FAILED\n{result.stderr}"
        except subprocess.TimeoutExpired:
            return "FAILED\nTimeoutError: Code execution exceeded 5 seconds."
        except Exception as e:
            return f"FAILED\nSystemError: {str(e)}"
        finally:
            if os.path.exists(temp_path):
                os.remove(temp_path)

    def clean_code(self, raw_text: str):
        ticks = "`" * 3
        pattern = rf"{ticks}(?:python|py)?\s*(.*?)\s*{ticks}"
        code_blocks = re.findall(pattern, raw_text, re.DOTALL | re.IGNORECASE)
        return code_blocks[-1].strip() if code_blocks else raw_text.strip()

    @start()
    def init_sprint(self):
        self.state["sprint_count"] = 1
        self.state["feedback"] = ""
        self.state["best_code"] = ""
        print(f"\n--- Starting AgileCoder Development: Sprint {self.state['sprint_count']} ---")
        return self.run_sprint_crew()

    @listen("next_sprint")
    def execute_next_sprint(self):
        self.state["sprint_count"] += 1
        print(f"\n--- Initiating Sprint {self.state['sprint_count']} to fix bugs ---")
        return self.run_sprint_crew()

    def run_sprint_crew(self):
        # Pass the original requirement and the feedback from the previous sprint
        context = self.state["requirement"]
        if self.state["feedback"]:
            context += f"\n\n### PREVIOUS SPRINT FAILED ###\nError Log:\n{self.state['feedback']}\n\nPlease fix the logic in this sprint."

        result = AgileCoderCrew().crew().kickoff(inputs={"requirement": context})

        # Extract the outputs generated by the specific tasks
        self.state["latest_code"] = self.clean_code(result.tasks_output[2].raw) # Implementation Task
        self.state["latest_tests"] = self.clean_code(result.tasks_output[4].raw) # Verification Task

        # Save the code just in case it's the last sprint
        if not self.state["best_code"]:
            self.state["best_code"] = self.state["latest_code"]

        return "check_results"

    @router(or_(init_sprint, execute_next_sprint))
    def evaluate_sprint(self):
        print("[*] Testing Software in Deterministic Sandbox...")

        execution_result = self.execute_code_deterministically(
            self.state["latest_code"],
            self.state["latest_tests"]
        )

        if execution_result == "PASSED":
            print("[+] Sprint Successful! All tests passed.")
            self.state["best_code"] = self.state["latest_code"]
            return "wrap_up"

        print("[!] Sprint Failed to meet acceptance criteria.")
        self.state["feedback"] = execution_result

        if self.state["sprint_count"] < self.MAX_SPRINTS:
            return "next_sprint"

        print("[!] Max Sprints Reached. Terminating development.")
        self.state["best_code"] = self.state["latest_code"]
        return "wrap_up"

    @listen("wrap_up")
    def final_code_extraction(self):
        print("[*] Packaging final deliverable...")
        return self.state["best_code"]